# Generated by Django 4.0.3 on 2022-04-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_leader', models.CharField(max_length=20)),
                ('student_1', models.CharField(max_length=20)),
                ('student_2', models.CharField(max_length=20)),
                ('section', models.CharField(choices=[('', ''), ('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=3)),
                ('password', models.CharField(max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=3)),
                ('password', models.CharField(max_length=15)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('selected_by', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
