# Generated by Django 4.0.3 on 2022-04-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_topics_selected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='selected_by',
            field=models.CharField(default='none', max_length=4),
        ),
    ]
