# Generated by Django 4.0.4 on 2022-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_topics_selected_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNewTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('batchid', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='GetTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=15)),
                ('selected_by', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('batchid', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
    ]
