# Generated by Django 4.0.4 on 2022-05-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_addnewtopic_gettopics_selectedtopics_delete_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='AddNewTopic',
        ),
        migrations.AlterField(
            model_name='gettopics',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='gettopics',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
