# Generated by Django 4.0.4 on 2022-05-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_adminlogin_delete_addnewtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlogin',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
