# Generated by Django 4.0.4 on 2022-05-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_gettopics_selected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettopics',
            name='selected_by',
            field=models.CharField(default='', max_length=3),
        ),
    ]
