# Generated by Django 4.0.4 on 2022-05-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_gettopics_selected_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1500)),
                ('selected_by', models.CharField(max_length=3)),
            ],
        ),
    ]
