# Generated by Django 4.0.4 on 2022-05-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_addtopics_selected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtopics',
            name='selected_by',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
