# Generated by Django 4.0.4 on 2022-05-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_addtopics_selected_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTopics',
        ),
    ]
