# Generated by Django 4.0.4 on 2022-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_addtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettopics',
            name='selected_by',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
