# Generated by Django 4.0.3 on 2022-05-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userinhome'),
        ('main', '0018_alter_gettopics_selected_by'),
    ]

    operations = [
    ]
