# Generated by Django 4.0.3 on 2022-05-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_20220518_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInHome',
        ),
        migrations.AddField(
            model_name='gettopics',
            name='faculty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
