# Generated by Django 4.0.3 on 2022-05-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_authtoken_studenttopicacceptreject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
